[package]
name = "envrbw"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "envrbw"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rpassword = "7"
spinners = "4"
