[package]
name = "bwenv"
version = "0.1.2"
edition = "2024"

[[bin]]
name = "bwenv"
path = "src/main.rs"

[dependencies]
clap = { version = "4", features = ["derive"] }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
rpassword = "7"
spinners = "4"
